-- TESIVIL Database Schema v5.0
-- Based on Master Plan Chapter 5 & 6

-- 1. ENUMS & TYPES
create type public.subscription_status as enum ('FREE', 'PRO');
create type public.economic_zone as enum ('ZONE_FREE_NORTH', 'ZONE_GENERAL');
create type public.confidence_level as enum ('HIGH', 'MEDIUM', 'LOW');
create type public.quote_status as enum ('DRAFT', 'FINALIZED');
create type public.material_category as enum ('MATERIAL', 'RENTAL', 'SERVICE');
create type public.report_status as enum ('PENDING', 'APPROVED', 'REJECTED');

-- 2. USERS TABLE (Profiles)
-- Extends Supabase auth.users
create table public.users (
  id uuid references auth.users(id) on delete cascade primary key,
  plan_type public.subscription_status default 'FREE',
  subscription_expiry timestamptz,
  economic_zone public.economic_zone default 'ZONE_GENERAL',
  reputation_score integer default 0,
  overhead_percent real default 30.0,
  profit_percent real default 30.0,
  technician_hourly_rate real default 0.0,
  helper_hourly_rate real default 0.0,
  last_sync_at timestamptz,
  referral_code text unique,
  referral_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. MATERIALS TABLE (Master Catalog)
-- "The Critical 50"
create table public.materials (
  id bigint generated by default as identity primary key,
  name text not null,
  category_type public.material_category default 'MATERIAL',
  base_price integer not null, -- Stored in cents/integers
  price_min_limit integer not null,
  price_max_limit integer not null,
  book_time_index integer default 0, -- Standard minutes
  confidence_level public.confidence_level default 'MEDIUM',
  volatility_score real default 0.0,
  manual_override boolean default false,
  last_verified_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Search index for materials
create index materials_name_idx on public.materials using gin(to_tsvector('spanish', name));

-- 4. USER PRICE REPORTS (Crowdsourcing)
create table public.user_price_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) not null,
  material_id bigint references public.materials(id) not null,
  reported_price integer not null,
  evidence_url text,
  status public.report_status default 'PENDING',
  created_at timestamptz default now()
);

-- 5. ASSEMBLIES (Kits)
create table public.assemblies (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  base_labor_minutes integer default 0,
  created_at timestamptz default now()
);

create table public.assembly_definitions (
  id bigint generated by default as identity primary key,
  assembly_id bigint references public.assemblies(id) on delete cascade,
  material_id bigint references public.materials(id),
  quantity integer default 1,
  is_main_component boolean default false
);

-- 6. QUOTES (Operative Context)
create table public.quotes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) not null,
  status public.quote_status default 'DRAFT',
  logistics_tier integer default 0, -- 0: Local, 1: Periphery, 2: Foreign
  obstruction_factor real default 1.0,
  difficulty_factor real default 1.0,
  is_urgent boolean default false,
  system_labor_total integer default 0, -- In cents or minutes? Plan says "Horas calculadas", likely minutes or cost. Assuming Cost in cents for consistency or Minutes. Plan says "System Labor Total" (REAL) in table def but "Calculo basado en enteros" in Ch 3. Let's use INTEGER for cents.
  user_labor_override integer, -- Manual adjustment in cents
  project_name text,
  client_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. QUOTE ITEMS (Details)
create table public.quote_items (
  id uuid default gen_random_uuid() primary key,
  quote_id uuid references public.quotes(id) on delete cascade not null,
  material_id bigint references public.materials(id),
  quantity integer default 1,
  client_supplied boolean default false,
  frozen_unit_price integer, -- Price snapshot at time of quote
  calculated_labor integer, -- Labor cost snapshot
  created_at timestamptz default now()
);

-- 8. QUOTE SNAPSHOTS (Immutable Archive)
create table public.quote_snapshots (
  id uuid default gen_random_uuid() primary key,
  quote_id uuid references public.quotes(id) on delete cascade,
  user_id uuid references public.users(id), -- Denormalized for faster RLS
  snapshot_json jsonb not null,
  pdf_url text,
  created_at timestamptz default now()
);

-- 9. SECURITY (RLS)
alter table public.users enable row level security;
alter table public.materials enable row level security;
alter table public.user_price_reports enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;
alter table public.quote_snapshots enable row level security;

-- USERS Policies
create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

-- MATERIALS Policies
create policy "Materials are public read" on public.materials
  for select using (true);
-- No write access for normal users

-- QUOTES Policies
create policy "Users can CRUD own quotes" on public.quotes
  for select using (auth.uid() = user_id);

create policy "Users can insert own quotes" on public.quotes
  for insert with check (auth.uid() = user_id);

create policy "Users can update own non-finalized quotes" on public.quotes
  for update using (
    auth.uid() = user_id
    and status != 'FINALIZED'
  )
  with check (
    status != 'FINALIZED' -- Prevent updating TO finalized? No, prevent updating attributes IF already finalized. 
    -- Actually, usually we allow transitioning TO finalized key.
    -- The WHERE clause filters rows that ARE finalized. So if status is FINALIZED, you can't see it for update.
  );

create policy "Users can delete own non-finalized quotes" on public.quotes
  for delete using (
    auth.uid() = user_id 
    and status != 'FINALIZED'
  );

-- QUOTE ITEMS Policies
create policy "Users can CRUD own quote items" on public.quote_items
  for all using (
    exists (
      select 1 from public.quotes q
      where q.id = quote_items.quote_id
      and q.user_id = auth.uid()
    )
  );

-- SNAPSHOT Policies (Insert Only for Users, Read Own)
create policy "Users can insert snapshots" on public.quote_snapshots
  for insert with check (
    -- Can only insert if they own the related quote (optional check via subquery or trust user_id param)
    auth.uid() = user_id
  );

create policy "Users can view own snapshots" on public.quote_snapshots
  for select using (auth.uid() = user_id);

-- Prevent modification of snapshots
-- (RLS Default is deny all, so we just don't add UPDATE/DELETE policies)

-- 10. FUNCTIONS
-- Auto-update updated_at timestamp
create extension if not exists moddatetime schema extensions;

create trigger handle_updated_at before update on public.users
  for each row execute procedure moddatetime (updated_at);

create trigger handle_updated_at before update on public.materials
  for each row execute procedure moddatetime (updated_at);

create trigger handle_updated_at before update on public.quotes
  for each row execute procedure moddatetime (updated_at);
